name       : rpm
version    : 4.16.1.3
release    : 18
source     :
    - http://ftp.rpm.org/releases/rpm-4.16.x/rpm-4.16.1.3.tar.bz2 : 513dc7f972b6e7ccfc9fc7f9c01d5310cc56ee853892e4314fa2cad71478e21d
license    : LGPL-2.0-or-later
component  : programming.devel
summary    : RPM Package Manager
description: |
    The RPM Package Manager (RPM) is a powerful command line driven package management system capable of installing, uninstalling, verifying, querying, and updating software packages. Each software package consists of an archive of files along with information about the package like its version, a description, etc.

    The RPM Package Manager is provided in Solus to enable building RPM for RPM-based Linux distributions from Solus using tools like 'mock'. To build packages for Solus, use 'ypkg' and 'solbuild'.
builddeps  :
    - pkgconfig(libacl)
    - pkgconfig(libarchive)
    - pkgconfig(libcap)
    - pkgconfig(libelf)
    - pkgconfig(liblzma)
    - pkgconfig(libzstd)
    - pkgconfig(lua)
    - pkgconfig(nspr)
    - pkgconfig(nss)
    - pkgconfig(openssl)
    - pkgconfig(popt)
    - pkgconfig(python3)
    - pkgconfig(zlib)
    - bzip2-devel
    - db5-devel
    - elfutils-devel
setup      : |
    # Disable plugins: Don't want systemd-inhibit running in chroot builds
    %reconfigure \
        --disable-plugins \
        --disable-static \
        --enable-nls \
        --enable-python \
        --with-acl \
        --with-cap \
        --with-external-db \
        --with-lua \
        --with-path-magic=/usr/share/file/magic.mgc \
        --with-vendor=solus \
        CFLAGS="$CFLAGS -DLUA_COMPAT_ALL -DLUA_COMPAT_MODULE" CPPFLAGS="-I/usr/include/nspr -I/usr/include/nss"
    %make

    pushd python
        python3 setup.py build
    popd
install    : |
    %make_install
    pushd python
        python3 setup.py install --root=$installdir
    popd
    rm -rf $installdir/var
