name       : rpm
version    : 4.14.0
release    : 8
source     :
    - http://ftp.rpm.org/releases/rpm-4.14.x/rpm-4.14.0.tar.bz2 : 06a0ad54600d3c42e42e02701697a8857dc4b639f6476edefffa714d9f496314
license    : LGPL-2.0-or-later
component  : programming.devel
summary    : RPM Package Manager
description: |
    The RPM Package Manager (RPM) is a powerful command line driven
    package management system capable of installing, uninstalling,
    verifying, querying, and updating software packages. Each software
    package consists of an archive of files along with information about
    the package like its version, a description, etc.

    The RPM Package Manager is provided in Solus to enable building RPMs
    for RPM-based Linux distributions from Solus using tools like 'mock'.
    To build packages for Solus, use 'ypkg' and 'solbuild'.
builddeps  :
    - pkgconfig(libarchive)
    - pkgconfig(libcap)
    - pkgconfig(libelf)
    - pkgconfig(liblzma)
    - pkgconfig(libzstd)
    - pkgconfig(lua)
    - pkgconfig(nspr)
    - pkgconfig(nss)
    - pkgconfig(openssl)
    - pkgconfig(popt)
    - pkgconfig(python3)
    - pkgconfig(zlib)
    - acl-devel
    - bzip2-devel
    - db5-devel
    - elfutils-devel
setup      : |
    # Disable plugins: Don't want systemd-inhibit running in chroot builds
    %configure \
        --disable-plugins \
        --disable-static \
        --enable-nls \
        --enable-python \
        --with-acl \
        --with-cap \
        --with-external-db \
        --with-lua \
        --with-path-magic=/usr/share/file/magic.mgc \
        --with-vendor=solus \
        CFLAGS="$CFLAGS -DLUA_COMPAT_ALL -DLUA_COMPAT_MODULE" CPPFLAGS="-I/usr/include/nspr -I/usr/include/nss"
    %make

    pushd python
        python2 setup.py build
        python3 setup.py build
    popd
install    : |
    %make_install
    pushd python
        python2 setup.py install --root=$installdir
        python3 setup.py install --root=$installdir
    popd
    rm -rvf $installdir/var
