name       : rpm
version    : 4.12.0.1
release    : 2
source     :
    - http://rpm.org/releases/rpm-4.12.x/rpm-4.12.0.1.tar.bz2 : 77ddd228fc332193c874aa0b424f41db1ff8b7edbb6a338703ef747851f50229
license    : GPL-2.0
summary    : RPM Package Manager
description: |
    RPM Package Manager
builddeps  :
    - pkgconfig(nspr)
    - pkgconfig(nss)
    - pkgconfig(openssl)
    - pkgconfig(python-2.7)
    - db5-devel
setup      : |
    # Disable LUA: Not needed at all in any context for Solus..
    # Disable plugins: Don't want systemd-inhibit running in chroot builds
    %configure \
        --disable-static \
        --with-external-db \
        --without-lua \
        --disable-plugins \
        --with-path-magic=/usr/share/file/magic.mgc \
        --enable-python \
        CPPFLAGS="-I/usr/include/nspr -I/usr/include/nss"
    %make
install    : |
    %make_install
    rm -rvf $installdir/var
